<a href="https://colab.research.google.com/github/maggieshiro384-art/CDAV/blob/main/Social_media_impact_on_mental_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

PANDAS

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
#a series is a list that grew up:it carries labels on the left and single dtypes at the bottom

counties=pd.Series([4397073,1208333,2162202,1157873])
print(counties)

0    4397073
1    1208333
2    2162202
3    1157873
dtype: int64

In [ ]:
df = pd.read_csv("/content/Untitled spreadsheet - Sheet1.csv")
df.head() #df.head() shows the first five values when its empty to see other rows you put a number you want e.g df.head(10)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [ ]:
df.tail() #df.head() shows the last five values when its empty to see other rows you put a number you want e.g df.tail(10)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [ ]:
df.shape # shows how many rows and columns you have in a data set

(1200, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [ ]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

df.column
df.dtype
df.index
df.size..........this are attributes

df.[].unique()
df.[].ununique()........this are methods

In [ ]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [ ]:
df.dtypes

age                           int64
gender                       object
daily_social_media_hours    float64
platform_usage               object
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level     object
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=1200, step=1)

In [ ]:
df.size

15600

In [ ]:
#this is a method
#good for checking outlier

df["age"].unique()

array([14, 19, 17, 15, 18, 16, 13])

In [ ]:
#this is a method
df["age"].nunique()

7

#Selecting columns
We select columns because we want to work on the data bit by bit

count the brackets.one pair gives you a series. two-pairs and more a list of names inside inside the brackets-gives you a dataframe

In [ ]:
df["age"]

0       14
1       19
2       17
3       15
4       15
        ..
1195    18
1196    16
1197    14
1198    15
1199    16
Name: age, Length: 1200, dtype: int64

In [ ]:
df[["age","gender"]]

      age  gender
0      14    male
1      19  female
2      17  female
3      15    male
4      15  female
...   ...     ...
1195   18  female
1196   16    male
1197   14  female
1198   15    male
1199   16  female

[1200 rows x 2 columns]

In [ ]:
df[["age","gender","anxiety_level"]]

      age  gender  anxiety_level
0      14    male              2
1      19  female              1
2      17  female              4
3      15    male              7
4      15  female              5
...   ...     ...            ...
1195   18  female              4
1196   16    male              4
1197   14  female              1
1198   15    male              9
1199   16  female              7

[1200 rows x 3 columns]

#.loc and .iloc
df.loc-select by the name you can see-row labels and column names
df.iloc-select by position-counting

In [ ]:
df.loc[2,"age"]  #row labelled 2, column named age. it allows for you to look by name eg.age

np.int64(17)

In [ ]:
df.iloc[2,0]   #third row,first column. allows you to look for something by index

np.int64(17)

In [ ]:
df.loc[0]

0       14
1       19
2       17
3       15
4       15
        ..
1195    18
1196    16
1197    14
1198    15
1199    16
Name: age, Length: 1200, dtype: int64

In [ ]:
df.loc[0:2]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0

In [ ]:
df.loc[:, "age"]

0       14
1       19
2       17
3       15
4       15
        ..
1195    18
1196    16
1197    14
1198    15
1199    16
Name: age, Length: 1200, dtype: int64

.iloc excludes the endpoint, exactly like the list slicing. Two methods two different rules

In [ ]:
df.iloc[0] # first row

age                                14
gender                           male
daily_social_media_hours          7.9
platform_usage              Instagram
sleep_hours                       7.4
screen_time_before_sleep          2.9
academic_performance             3.01
physical_activity                 1.5
social_interaction_level          low
stress_level                        2
anxiety_level                       2
addiction_level                     1
depression_label                    0
Name: 0, dtype: object

In [ ]:
df.iloc[0:2] # rows 0 and 1- not row 2

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0

In [ ]:
df.iloc[-1]#last row

age                             16
gender                      female
daily_social_media_hours       4.7
platform_usage              TikTok
sleep_hours                    6.5
screen_time_before_sleep       1.0
academic_performance          2.91
physical_activity              0.9
social_interaction_level    medium
stress_level                     5
anxiety_level                    7
addiction_level                  3
depression_label                 0
Name: 1199, dtype: object

In [ ]:
df.iloc[0:3, 0:2]#first 3 rows, first two columns

   age  gender
0   14    male
1   19  female
2   17  female

In [12]:
import pandas as pd
df = pd.read_csv("/content/Untitled spreadsheet - Sheet1 (1).csv")

In [13]:
df=pd.read_csv("/content/Untitled spreadsheet - Sheet1 (1).csv")

In [14]:
df["gender"]!="female"

0        True
1       False
2       False
3        True
4       False
        ...
1195    False
1196     True
1197    False
1198     True
1199    False
Name: gender, Length: 1200, dtype: bool

In [21]:
df["age"]<18

0        True
1       False
2        True
3        True
4        True
        ...
1195    False
1196     True
1197     True
1198     True
1199     True
Name: age, Length: 1200, dtype: bool

In [22]:
df["gender"]=="female"

0       False
1        True
2        True
3       False
4        True
        ...
1195     True
1196    False
1197     True
1198    False
1199     True
Name: gender, Length: 1200, dtype: bool

In [20]:
s=pd.Series([10,25,30,45]) # a series has only one column
s>20

0    False
1     True
2     True
3     True
dtype: bool

In [19]:
is_gender=df["gender"]=="female"
age=df["age"]>18
df[is_gender & age]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
36,19,female,4.6,Instagram,5.5,2.5,3.96,0.8,high,3,10,7,0
64,19,female,7.9,TikTok,5.1,1.7,2.80,0.8,low,6,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,19,female,7.9,TikTok,5.8,2.1,3.91,1.4,high,7,1,10,0
1146,19,female,4.5,TikTok,8.4,2.1,2.62,2.0,low,5,10,5,0
1159,19,female,7.3,Instagram,7.8,1.0,2.91,0.8,medium,9,7,5,0
1178,19,female,3.5,Instagram,4.9,0.5,3.68,1.7,high,8,4,3,0
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0

In [23]:
is_gender=df["gender"]=="female"
is_greater=df["age"]>18
df[is_gender & is_greater]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
36,19,female,4.6,Instagram,5.5,2.5,3.96,0.8,high,3,10,7,0
64,19,female,7.9,TikTok,5.1,1.7,2.80,0.8,low,6,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,19,female,7.9,TikTok,5.8,2.1,3.91,1.4,high,7,1,10,0
1146,19,female,4.5,TikTok,8.4,2.1,2.62,2.0,low,5,10,5,0
1159,19,female,7.3,Instagram,7.8,1.0,2.91,0.8,medium,9,7,5,0
1178,19,female,3.5,Instagram,4.9,0.5,3.68,1.7,high,8,4,3,0
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0

In [29]:
is_greater=df[df["age"]>18] # .shape gives you the number of rows and columns of females above 18 years
is_greater.shape

(162, 13)

In [27]:
is_greater=df[df["age"]>18] #len()gives you the number of females who are above 18 years
len(is_greater)

162

# Two conditions at once

In [30]:
# females and over 18 years
df[(df["gender"]=="female") & (df["age"]>18)] # & means (and) but not use it as (and) use it as & in pandas
# both conditions have to be true for you to get an output

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
36,19,female,4.6,Instagram,5.5,2.5,3.96,0.8,high,3,10,7,0
64,19,female,7.9,TikTok,5.1,1.7,2.80,0.8,low,6,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,19,female,7.9,TikTok,5.8,2.1,3.91,1.4,high,7,1,10,0
1146,19,female,4.5,TikTok,8.4,2.1,2.62,2.0,low,5,10,5,0
1159,19,female,7.3,Instagram,7.8,1.0,2.91,0.8,medium,9,7,5,0
1178,19,female,3.5,Instagram,4.9,0.5,3.68,1.7,high,8,4,3,0
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0

In [31]:
df[(df["gender"]=="female")|(df["age"]>18)] # | means or but not use it as or use it as | in pandas

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1193,13,female,7.2,Instagram,8.1,2.1,2.52,0.4,medium,3,3,7,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

#Not, and one-of-many
one can use the parameters eg ==,<>,<==,>== or use .isin()---method

In [46]:
# not gender (~)sign means 'not'
df[~(df["gender"] == "female")]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
10,16,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5,8,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1192,13,male,7.8,TikTok,5.9,1.5,3.31,1.9,high,10,1,10,0
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0

In [47]:
df[~df["gender"].isin(["female"])]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
10,16,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5,8,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1192,13,male,7.8,TikTok,5.9,1.5,3.31,1.9,high,10,1,10,0
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0

In [36]:
df[df["age"].isin([14,15,16])]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

#Ranges and a readable alternative
.query() reads more easily and lets you use the word (and) again. it is slower on small data and awkward when column names contain spaces so learn both.
It uses (.between)

In [43]:
# between-exclusive at both ends
df[df["age"].between(14,18)]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [45]:
# query-the same filter written as a sentence
df.query("gender=='female' and age>18")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
36,19,female,4.6,Instagram,5.5,2.5,3.96,0.8,high,3,10,7,0
64,19,female,7.9,TikTok,5.1,1.7,2.80,0.8,low,6,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,19,female,7.9,TikTok,5.8,2.1,3.91,1.4,high,7,1,10,0
1146,19,female,4.5,TikTok,8.4,2.1,2.62,2.0,low,5,10,5,0
1159,19,female,7.3,Instagram,7.8,1.0,2.91,0.8,medium,9,7,5,0
1178,19,female,3.5,Instagram,4.9,0.5,3.68,1.7,high,8,4,3,0
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0

#Before you filter see what is there.
never filter for a value you have not confirmed exists
using .value_counts() one is able to flag mistakes

In [48]:
df["gender"].value_counts() # its a good way to get counts

gender
male      615
female    585
Name: count, dtype: int64

In [49]:
df["gender"].value_counts(dropna=False) #counts missing value

gender
male      615
female    585
Name: count, dtype: int64

In [50]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [51]:
df["gender"].nunique()

2

#Data cleaning
is the process of finding and fixing errors in data
## Missing data
in pandas NaN is not zero-panda is saying "we do not know whats going on here
0=zer0-we do know and the answer is zero
''-a real value is missing

df.isna().sum is the line you will typeon every dataset you ever load.

In [52]:
df.isna().sum()# counts null-values per column

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [53]:
df.isna()# True where a value is missing

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False

In [54]:
df.isna().sum().sum()# total across all table

np.int64(0)

In [55]:
df.isna().mean()*100 #percentage missing per column

age                         0.0
gender                      0.0
daily_social_media_hours    0.0
platform_usage              0.0
sleep_hours                 0.0
screen_time_before_sleep    0.0
academic_performance        0.0
physical_activity           0.0
social_interaction_level    0.0
stress_level                0.0
anxiety_level               0.0
addiction_level             0.0
depression_label            0.0
dtype: float64

In [58]:
df[df["gender"].isna()]

Empty DataFrame
Columns: [age, gender, daily_social_media_hours, platform_usage, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity, social_interaction_level, stress_level, anxiety_level, addiction_level, depression_label]
Index: []

#Deleting:dropna()
check the shape before and after, every single time. plain dropna() on a wide
instead of dropping the columns you can use the central tendancies eg mode,median , mean.
if you use df.dropna() Pandas will delete the entire row containing the missing value:
If you want to remove only rows where a specific column is missing
df.dropna(subset=["age"]
If you only want to drop a specific column
df.dropna(subset=["age"])

Filling:fillna()
If you want to keep the row and fill in the missing value

For example, fill the missing age with 14 df["age"] = df["age"].fillna(14)
Or fill the missing age with the average age:df["age"] = df["age"].fillna(df["age"].mean())

Finding and Removing duplicates

In [61]:
df.duplicated().sum()   #checks for how many repeated entries are there

np.int64(0)

In [62]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, gender, daily_social_media_hours, platform_usage, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity, social_interaction_level, stress_level, anxiety_level, addiction_level, depression_label]
Index: []

In [63]:
df.drop_duplicates()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [64]:
df.drop_duplicates(subset=["age"])

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
11,13,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1,10,8,0

In [65]:
df.drop_duplicates(subset=["gender"])

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0

#Fixing column names
df.columns
df=df.rename(columns={"age":

#Replace bad value
still use .replace

#Dropping what you do not need

# Making a new column from a condition

#Changing values in place of .loc

#Data Types
Run df.dtypes before you trust a single number in a table

#Changing a type
errors="coerce" turns anything it cannot convert into NaN-which you already know how to find and handle.
df["amount"]=df["amount"].astype(float)
df["county]=df["county"].astype("category)
when astype fails because of junk values.
df["amount"]=pd.to_numeric(df["amount"], errors="coerce"

#Predict the output
s=pd.Series(["100","250","N/A","400"])
pd.to_numeric(s,error="coerce")

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("/content/Untitled spreadsheet - Sheet1 (1).csv")

In [6]:
 # the N/A becomes NaN because its a string and cannot be converted to a numeric (int or float).
#A NaN means pandas does not know what to do with it
s=pd.Series(["100","250","N/A","400"])
pd.to_numeric(s,errors="coerce")

0    100.0
1    250.0
2      NaN
3    400.0
dtype: float64

In [9]:
#Checks how many become NaN
df.isna().sum() # My output shows there is no NaN

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

# DATA CLEANING
##Laptopdata
The file contains "dirty" data that we are trying to clean

In [11]:
df = pd.read_csv("/content/laptopData.csv")

In [12]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [13]:
df.tail()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.64
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.72
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.12
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32

In [14]:
df.shape

(1303, 12)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [17]:
df.describe()

        Unnamed: 0          Price
count  1273.000000    1273.000000
mean    652.674784   59955.814073
std     376.493027   37332.251005
min       0.000000    9270.720000
25%     327.000000   31914.720000
50%     652.000000   52161.120000
75%     980.000000   79333.387200
max    1302.000000  324954.720000

In [20]:
df.isna().sum() # shows the null values

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(29)

In [22]:
df.select_dtypes("object").describe()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
count,1273,1273,1273,1273,1273,1273,1273,1273,1273,1273
unique,19,6,25,40,118,10,40,110,9,189
top,Lenovo,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg
freq,290,710,640,495,183,601,401,271,1047,111